apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: job-dashboard
data:
  DEBUG: "False"
  DB_NAME: "job_dashboard"
  DB_USER: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  ALLOWED_HOSTS: "backend-service,localhost,127.0.0.1"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://frontend-service:3000"