apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: job-dashboard
type: Opaque
data:
  # postgres (base64 encoded)
  DB_PASSWORD: cG9zdGdyZXM=
  # your-production-secret-key-change-this (base64 encoded)
  SECRET_KEY: eW91ci1wcm9kdWN0aW9uLXNlY3JldC1rZXktY2hhbmdlLXRoaXM=