apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: job-dashboard
type: Opaque
data:
  # postgres / postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: am9iX2Rhc2hib2FyZA==